./convert.sh -i "XC1044888 - Red-chested Cuckoo - Cuculus solitarius.wav" -o cuckoo.mp3
./convert.sh -i "XC1053509 - Red-eyed Dove - Streptopelia semitorquata.wav" -o dove.mp3
./convert.sh -i "XC1059929 - Hadada Ibis - Bostrychia hagedash.wav" -o hadeda.mp3
./convert.sh -i "XC186140 - Cape Starling - Lamprotornis nitens.mp3" -o starling.mp3
./convert.sh -i "XC267222 - Southern Boubou - Laniarius ferrugineus.mp3" -o boubou.mp3
./convert.sh -i "XC292589 - Pied Crow - Corvus albus.mp3" -o crow.mp3
./convert.sh -i "XC416973 - Cape Robin-Chat - Cossypha caffra.mp3" -o robin.mp3
./convert.sh -i "XC428884 - Cape Canary - Serinus canicollis.mp3" -o canary.mp3
./convert.sh -i "XC444328 - Spotted Eagle-Owl - Bubo africanus.mp3" -o owl.mp3
./convert.sh -i "XC715717 - Fork-tailed Drongo - Dicrurus adsimilis.mp3" -o drongo.mp3
