FILENAME="cuckoo.raw"
exec(open('playaudio.py').read())
FILENAME="dove.raw"
exec(open('playaudio.py').read())
FILENAME="hadeda.raw"
exec(open('playaudio.py').read())
FILENAME="starling.raw"
exec(open('playaudio.py').read())
FILENAME="boubou.raw"
exec(open('playaudio.py').read())
FILENAME="crow.raw"
exec(open('playaudio.py').read())
FILENAME="robin.raw"
exec(open('playaudio.py').read())
FILENAME="canary.raw"
exec(open('playaudio.py').read())
FILENAME="owl.raw"
exec(open('playaudio.py').read())
FILENAME="drongo.raw"
exec(open('playaudio.py').read())
